### ISSUE TITLE
`/questions` command has duplicate sentence

### ISSUE THREAD

**Issue by winston-yallow** [winston-yallow/godot-discord-bot#12]
From the command:

> Helpers often ask you questions to better understand the problem. This makes it easier to understand your problem.

**Comment by bheyman-scottlogic** [comment]
Can I please work on this?

**Comment by winston-yallow** [comment]
@bheyman-scottlogic sure, feel free to submit a PR

**Comment by bheyman-scottlogic** [comment]
Im trying to get it running on a personal discord server to see how it works. Not sure where I get the `clientId` from in `config.js`

**Comment by winston-yallow** [comment]
You'll need to follow the setup guide:
https://github.com/winston-yallow/godot-discord-bot?tab=readme-ov-file#setup

The token is obtained by creating a discord application as explained in the linked [discord.js guide](https://discordjs.guide/preparations/setting-up-a-bot-application.html#creating-your-bot).

**Comment by winston-yallow** [comment]
Fixed by #13
